# Generated by Django 2.2.15 on 2020-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201004_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='brawler@abv.bg', max_length=254, verbose_name='email address'),
            preserve_default=False,
        ),
    ]
